ccs-calendarserver: Address build issues with newer dependencies
* Update to openssl 1.0.2r in ./bin/_build.sh
* Update to sqlparse 0.2.4 in ./requirements-cs.txt
* **WARNING**: Does not yet address `invoke './Configure darwin64-x86_64-cc' *manually*` in `.develop/src/openssl-1.0.2r/config`, `ld: symbol(s) not found for architecture i386` errors
* See: https://gist.github.com/essandess/4c9b5d906896ff4aef6170fc18f2c293

Comments:
* OpenSSL build issues may be sidestepped by using the MacPorts (or other) openssl installs as system libraries. This is preferred to using a package-specific library that may not be upgraded as regularly as its dependency. Working example that yields a successful run of `./bin/package /path/to/CalendarServer`:
```
export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
export C_INCLUDE_PATH=/opt/local/include
export LD_LIBRARY_PATH=/opt/local/lib:/opt/local/lib/openssl-1.0
export CPPFLAGS='-I/opt/local/include'
export LDFLAGS='-L/opt/local/lib -L/opt/local/lib/openssl-1.0'
export DYLD_LIBRARY_PATH=/opt/local/lib:/opt/local/lib/openssl-1.0

sh -E -x -c './bin/package -F /private/var/CalendarServer 1> ~/ccs-calendarserver.log 2>&1'
```